### ISSUE TITLE
Unable to purchase oak_log

### ISSUE THREAD

**Issue by Patrick228** [PurpleStormCloud/HyperMerchant-LifeSupport#1]
When using /buy oak_log (#)  no error message is returned in-game or in the console. Plugin responds as if no command was issued. Same holds true for all log types

**Comment by PurpleStormCloud** [comment]
This command is added by HyperConomy not HyperMerchant. If you need a 1.13 compatible HyperConomy you will have to use `OTG-HyperConomy-Lifesupport`, any other configuration is not supported by us.
